INSERT INTO quotes (text, author) VALUES
('You do not rise to the level of your goals. You fall to the level of your systems.', 'James Clear'),
('Every action you take is a vote for the type of person you wish to become.', 'James Clear'),
('The most practical thing you can do is to be deliberate about the habits you encourage.', 'James Clear'),
('Success is not final, failure is not fatal: it is the courage to continue that counts.', 'Winston Churchill'),
('It does not matter how slowly you go as long as you do not stop.', 'Confucius'),
('The impediment to action advances action. What stands in the way becomes the way.', 'Marcus Aurelius'),
('You have power over your mind, not outside events. Realize this, and you will find strength.', 'Marcus Aurelius'),
('Waste no more time arguing about what a good man should be. Be one.', 'Marcus Aurelius'),
('The secret of getting ahead is getting started.', 'Mark Twain'),
('Do what you can, with what you have, where you are.', 'Theodore Roosevelt'),
('It always seems impossible until it''s done.', 'Nelson Mandela'),
('Don''t watch the clock; do what it does. Keep going.', 'Sam Levenson'),
('The only way to do great work is to love what you do.', 'Steve Jobs'),
('In the middle of every difficulty lies opportunity.', 'Albert Einstein'),
('Believe you can and you''re halfway there.', 'Theodore Roosevelt'),
('Start where you are. Use what you have. Do what you can.', 'Arthur Ashe'),
('The future depends on what you do today.', 'Mahatma Gandhi'),
('Act well at the moment, and you have performed a good action for all eternity.', 'Johann Kaspar Lavater'),
('Small daily improvements over time lead to stunning results.', 'Robin Sharma'),
('Focus on being productive instead of busy.', 'Tim Ferriss');
